name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: npm install, build
        run: | 
          make install
      - name: Run Linter
        run: |
          npx eslint .
      - name: test
        run: |
          make test
      - name: Test & publish code coverage

        uses: paambaati/codeclimate-action@v2.6.0
        
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
       
      

